/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:70ec09b0-36e2-4cbb-83ab-ccabea8b55d0",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_7n93vEuTA",
    "aws_user_pools_web_client_id": "4viiju3i1a7un2q872jcvtsbd",
    "oauth": {}
};


export default awsmobile;
